/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haier_tms_jni_NativeAlgorithm */

#ifndef _Included_com_haier_tms_jni_NativeAlgorithm
#define _Included_com_haier_tms_jni_NativeAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haier_tms_jni_NativeAlgorithm
 * Method:    binPackingAlgorithm
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_haier_tms_jni_NativeAlgorithm_binPackingAlgorithm
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
